### ISSUE TITLE
Couldn't find youtube-dl

### ISSUE THREAD

**Issue by sallyhaj** [yucefsourani/pysavetube#1]
Hello there,
I use the ./pysavetube.py to run the app, but asks for installing 'youtube-dl', I have 'youtube-dl-2021.06.06-1.fc34.noarch'  package installed.
Thanks

**Comment by yucefsourani** [comment]
Hello,
Away from the system libraries pysavetube will install and update youtube-dl  from its official source in custom location ( ~/.local/share/pysavetube)  ,  ,this makes it easier to keep youtube-dl  up-to-date  especially if it is packaged as flatpak .

To install youtube-dl in ~/.local/share/pysavetube  click on  "install youtube-dl"  button.

https://github.com/yucefsourani/pysavetube/blob/master/pysavetube.py#L49

https://github.com/yucefsourani/pysavetube/blob/master/pysavetube.py#L1102

https://github.com/yucefsourani/pysavetube/blob/master/pysavetube.py#L1123
